// ============================================================
// Static Data — used for seeding Supabase & fallback rendering
// ============================================================

import type { Service, Project, Certification } from './types'

export const SERVICES_DATA: Omit<Service, 'id' | 'created_at' | 'updated_at'>[] = [
  {
    title: 'Design & Engineering',
    slug: 'design-engineering',
    description:
      'Comprehensive electrical power system design including substations, transmission lines, distribution systems, and renewable energy facilities.',
    icon: 'zap',
    order_index: 1,
  },
  {
    title: 'Project & Construction Management',
    slug: 'project-construction-management',
    description:
      'End-to-end project management and construction oversight for electric power infrastructure, from planning through commissioning.',
    icon: 'hard-hat',
    order_index: 2,
  },
  {
    title: 'Specifications & Procurement',
    slug: 'specifications-procurement',
    description:
      'Technical specification development and procurement support for electrical equipment, materials, and systems.',
    icon: 'clipboard-list',
    order_index: 3,
  },
  {
    title: 'Training & Knowledge Transfer',
    slug: 'training-knowledge-transfer',
    description:
      'Professional training programs and knowledge transfer sessions tailored for utility engineers and operations staff.',
    icon: 'graduation-cap',
    order_index: 4,
  },
  {
    title: 'Quality Assurance & Control',
    slug: 'quality-assurance-control',
    description:
      'Rigorous QA/QC programs ensuring engineering deliverables and construction work meet the highest industry standards.',
    icon: 'shield-check',
    order_index: 5,
  },
]

export const PROJECTS_DATA: Omit<Project, 'id' | 'created_at' | 'updated_at'>[] = [
  {
    title: '2025 Tar Pit Assessment at 2600 Wilshire',
    client: 'Housing Authority City of Los Angeles',
    slug: '2025-tar-pit-assessment-wilshire',
    description: 'Comprehensive tar pit assessment and environmental engineering services.',
    image_url: 'https://kewocorp.com/wp-content/uploads/2025/04/tar_pit_assestment_willshore_poster-300x214.jpg',
    video_url: null,
    category: 'Design & Engineering',
    tags: ['environmental', 'assessment'],
    featured: true,
    order_index: 1,
  },
  {
    title: 'Electric Vehicle, Energy Storage and Solar Infrastructure Project Management',
    client: 'City of Thousand Oaks',
    slug: 'ev-energy-storage-solar-thousand-oaks',
    description: 'Project management for EV charging, battery energy storage systems, and solar installations.',
    image_url: 'https://kewocorp.com/wp-content/uploads/2025/04/DJI_0155-300x214.jpg',
    video_url: null,
    category: 'Project & Construction Management',
    tags: ['EV', 'solar', 'BESS'],
    featured: true,
    order_index: 2,
  },
  {
    title: "Owners Engineering for Glenarm 25MW BESS Project",
    client: 'Pasadena Water and Power',
    slug: 'glenarm-25mw-bess-owners-engineering',
    description: "Owner's engineering services for a 25MW battery energy storage system project.",
    image_url: 'https://kewocorp.com/wp-content/uploads/2025/03/Owners-Engineering-BESS-PWP-300x214.jpg',
    video_url: null,
    category: 'Design & Engineering',
    tags: ['BESS', 'energy storage'],
    featured: true,
    order_index: 3,
  },
  {
    title: 'Mobile Substation Specification',
    client: 'Pasadena Water and Power',
    slug: 'pwp-mobile-substation-specification',
    description: 'Technical specification development for mobile substation equipment.',
    image_url: 'https://kewocorp.com/wp-content/uploads/2025/04/PWP-300x214.jpg',
    video_url: null,
    category: 'Specifications & Procurement',
    tags: ['substation', 'specification'],
    featured: false,
    order_index: 4,
  },
  {
    title: 'Electric Vehicle Charger Design',
    client: 'City of Anaheim',
    slug: 'anaheim-ev-charger-design',
    description: 'Electrical design services for EV charging infrastructure.',
    image_url: 'https://kewocorp.com/wp-content/uploads/2025/04/electric_vehicle_charger_design-221x214.png',
    video_url: null,
    category: 'Design & Engineering',
    tags: ['EV', 'charging'],
    featured: false,
    order_index: 5,
  },
  {
    title: 'Overhead-Underground Conversion',
    client: 'Cedars Sinai',
    slug: 'cedars-sinai-overhead-underground-conversion',
    description: 'Engineering design for overhead to underground power line conversion.',
    image_url: 'https://kewocorp.com/wp-content/uploads/2025/03/DJI_0374-300x214.jpg',
    video_url: null,
    category: 'Design & Engineering',
    tags: ['underground', 'conversion'],
    featured: false,
    order_index: 6,
  },
  {
    title: 'Electrical Design Services for Overhead Electrical Upgrades',
    client: 'City of Anaheim',
    slug: 'gsa-03-overhead-electrical-upgrades',
    description: 'Electrical design services for upgrading overhead electrical infrastructure.',
    image_url: 'https://kewocorp.com/wp-content/uploads/2024/07/Electrical_Design_Services_for_Overhead_Electrical_Upgrades_2-300x214.png',
    video_url: null,
    category: 'Design & Engineering',
    tags: ['overhead', 'upgrades'],
    featured: true,
    order_index: 7,
  },
  {
    title: 'Garland Solar Facility Conduit Design-Build for Centralized Remedial Action Scheme',
    client: 'LADWP',
    slug: 'garland-solar-facility-conduit-design-build',
    description: 'Conduit design-build for centralized remedial action scheme at Garland Solar Facility.',
    image_url: null,
    video_url: 'https://kewocorp.com/wp-content/uploads/2020/10/Garland-Coinduit-Revise-201127.mp4',
    category: 'Design & Engineering',
    tags: ['solar', 'conduit'],
    featured: true,
    order_index: 8,
  },
  {
    title: 'LAUS Terminal Remote and Mission Foundations',
    client: 'Metrolink',
    slug: 'laus-terminal-remote-mission-foundations',
    description: 'Foundation design engineering for terminal remote and mission control facilities.',
    image_url: null,
    video_url: null,
    category: 'Design & Engineering',
    tags: ['foundations', 'rail'],
    featured: false,
    order_index: 9,
  },
  {
    title: 'ZEB Master Plan (re)Visioning',
    client: 'Metro',
    slug: 'metro-zeb-master-plan-revisioning',
    description: 'Zero emission bus master plan development and strategic visioning.',
    image_url: null,
    video_url: null,
    category: 'Project & Construction Management',
    tags: ['ZEB', 'transit'],
    featured: false,
    order_index: 10,
  },
  {
    title: 'Maintenance Yards EV Charger Expansion',
    client: 'Pasadena Water and Power',
    slug: 'pwp-maintenance-yards-ev-charger-expansion',
    description: 'Expansion of EV charging infrastructure at utility maintenance yards.',
    image_url: 'https://kewocorp.com/wp-content/uploads/2025/03/Maintenance-EV-PWP-300x214.jpg',
    video_url: null,
    category: 'Design & Engineering',
    tags: ['EV', 'charging'],
    featured: false,
    order_index: 11,
  },
  {
    title: 'McCullough-Victorville Lines 1 and 2 Series Compensation Project',
    client: 'LADWP',
    slug: 'mccullough-victorville-series-compensation',
    description: 'Series compensation engineering for transmission lines 1 and 2.',
    image_url: null,
    video_url: null,
    category: 'Design & Engineering',
    tags: ['transmission', 'compensation'],
    featured: true,
    order_index: 12,
  },
]

export const CERTIFICATIONS_DATA: Omit<Certification, 'id' | 'created_at'>[] = [
  { name: 'SBE: Small Business Enterprise', number: '#732030', issuer: 'Port of Long Beach', order_index: 1 },
  { name: 'SB Micro: Small Business', number: '#1787885', issuer: 'Department of General Services (DGS OSDS)', order_index: 2 },
  { name: 'SLB: Small Local Business', number: '#SLB-3788', issuer: 'City of Los Angeles', order_index: 3 },
  { name: 'SBE: Small Business Enterprise', number: '#7317', issuer: 'LA Metro', order_index: 4 },
  { name: 'MBE: Micro Business Enterprise', number: '#900085238', issuer: 'LAUSD', order_index: 5 },
  { name: 'DBE: Disadvantaged Business Enterprise', number: '#42281', issuer: 'Caltrans', order_index: 6 },
  { name: 'EDE: Emerging Business Enterprise', number: '#1787885', issuer: 'Department of General Services', order_index: 7 },
  { name: 'LBE: Local Business Enterprise', number: null, issuer: 'City of Los Angeles', order_index: 8 },
  { name: 'MBE: Minority Owned Business Enterprise', number: '#42281', issuer: 'CUCP', order_index: 9 },
  { name: 'VSBE: Very Small Business Enterprise', number: '#1787885', issuer: 'DGS OSDS', order_index: 10 },
  { name: 'DIR: Department of Industrial Relations', number: '#1000027050', issuer: null, order_index: 11 },
  { name: 'EVITP: Electric Vehicle Infrastructure Training Program', number: '#4046696', issuer: null, order_index: 12 },
]

export const CLIENTS = [
  'LADWP', 'Southern California Edison', 'Pasadena Water & Power',
  'City of Anaheim', 'City of Thousand Oaks', 'LA Metro', 'Metrolink',
  'Port of Long Beach', 'Port of Oakland', 'LAUSD', 'Cedars Sinai',
  'DGS', 'GSA',
]
